test-jdk-8:
  image: openjdk:8
  script:
    - ./scripts/testrun.sh

test-jdk-9:
  image: openjdk:9
  script:
    - ./scripts/testrun.sh

test-jdk-10:
  image: openjdk:10
  script:
    - ./scripts/testrun.sh

test-jdk-11:
  image: openjdk:11
  script:
    - ./scripts/testrun.sh

test-jdk-12:
  image: openjdk:12
  script:
    - ./scripts/testrun.sh
