.test:
  script:
    - java -version
    - javac -version
    - ./gradlew -version
    - ./gradlew check jacocoTestReport javadoc shadowJar
  artifacts:
    paths:
      - build/docs
      - build/libs
      - build/reports
    expire_in: 1 week

lint:
  image: python:latest
  before_script:
    - pip install gitlint pre-commit
  script:
    - gitlint
    - pre-commit run --all-files

jdk8:
  extends: .test
  image: openjdk:8

jdk9:
  extends: .test
  image: openjdk:9

jdk10:
  extends: .test
  image: openjdk:10

jdk11:
  extends: .test
  image: openjdk:11

jdk12:
  extends: .test
  image: openjdk:12

jdk13:
  extends: .test
  image: openjdk:13
