.test:
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.cache/gradle"
  cache:
    paths:
      - $GRADLE_USER_HOME/caches
      - $GRADLE_USER_HOME/wrapper
  before_script:
    - java -version
    - javac -version
    - ./gradlew -version
  script:
    - ./gradlew check jacocoTestReport javadoc shadowJar
  artifacts:
    paths:
      - build/docs
      - build/libs
      - build/reports
    expire_in: 1 week

lint:
  image: python:3.8
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
    PYTHONUSERBASE: "$CI_PROJECT_DIR/.cache/python-user-packages"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - $PIP_CACHE_DIR
      - $PRE_COMMIT_HOME
      - $PYTHONUSERBASE
  before_script:
    - python -V
    - export PATH="$PATH:$PYTHONUSERBASE/bin"
    - pip install --user gitlint pre-commit
  script:
    - gitlint
    - pre-commit run --all-files

jdk8:
  extends: .test
  image: openjdk:8

jdk9:
  extends: .test
  image: openjdk:9

jdk10:
  extends: .test
  image: openjdk:10

jdk11:
  extends: .test
  image: openjdk:11

jdk12:
  extends: .test
  image: openjdk:12

jdk13:
  extends: .test
  image: openjdk:13

jdk14:
  extends: .test
  image: openjdk:14

jdk15:
  extends: .test
  image: openjdk:15

jdk16:
  extends: .test
  image: openjdk:16
