name: CI

on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install gitlint pre-commit
      - run: gitlint
      - run: pre-commit run --all-files
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 9, 10, 11, 12, 13, 14 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew check jacocoTestReport javadoc shadowJar
