name: CI

on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install gitlint pre-commit
      - run: gitlint
      - run: pre-commit run --all-files
  build:
    strategy:
      matrix:
        java:
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        architecture:
          - x64
          - x86
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
      - run: ./gradlew check jacocoTestReport javadoc shadowJar
