name: Test

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 * *' # monthly
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Build test
        run: ./gradlew build jacocoTestReport shadowJar

      - name: Publishing test
        run: ./gradlew publishToMavenLocal
